# **FlameFender ANN for Wildfire Risk Prediction**

**Step 1: Load packages and data**

In [ ]:
# 1
import numpy as np
import pandas as pd

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving replicate2TestData.csv to replicate2TestData.csv
Saving replicate2TrainData.csv to replicate2TrainData.csv

In [ ]:
# 2
# Load in csv files as dataframes
train = pd.read_csv('replicate2TrainData.csv')
test = pd.read_csv('replicate2TestData.csv')

df = pd.concat([train,test], axis=0, sort=True)
df.head()

,Dewpoint,Elevation,ForestFireIndex,Humidity,Latitude,Longitude,PrecipitationProbability,Temperature,WindSpeed
0,-14.444444,365.1504,1.0,10,34.1141,-118.4068,0,65,10
1,-17.777778,178.0032,0.0,66,41.8375,-87.6866,0,9,5
2,10.000000,2.1336,0.2,100,25.7840,-80.2101,0,50,6
3,-1.666667,17.9832,0.7,70,29.7860,-95.3885,0,38,5
4,-7.777778,153.9240,0.9,53,32.7935,-96.7667,0,33,0

In [ ]:
# 3
df.describe()

,Dewpoint,Elevation,ForestFireIndex,Humidity,Latitude,Longitude,PrecipitationProbability,Temperature,WindSpeed
count,679.000000,679.000000,543.000000,679.000000,679.000000,679.000000,679.000000,679.000000,679.000000
mean,-8.654066,255.827753,0.386188,64.455081,36.752474,-95.694959,2.487482,30.243004,4.801178
std,8.871400,388.432953,0.398536,24.009105,5.766644,17.681445,8.815852,16.838330,4.000029
min,-25.555556,-11.582400,0.000000,6.000000,18.012700,-157.846000,0.000000,-6.000000,0.000000
25%,-15.000000,28.956000,0.000000,57.000000,33.604750,-116.480750,0.000000,17.000000,2.000000
50%,-10.555556,132.892800,0.200000,71.000000,37.502500,-92.077400,0.000000,27.000000,5.000000
75%,-2.777778,271.576800,0.800000,80.000000,40.799350,-81.000900,0.000000,45.000000,6.000000
max,22.777778,2117.140800,1.000000,100.000000,64.835300,-65.979200,66.000000,76.000000,26.000000

**Step 2: Data preprocessing**

1) Encoding categorical values
2) Scaling continuous values

In [ ]:
# 4
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib.pyplot import rcParams
%matplotlib inline
rcParams['figure.figsize'] = 10,8
sns.set(style='whitegrid', palette='muted',
        rc={'figure.figsize': (15,10)})

In [ ]:
# 8
df.head()

,Dewpoint,Elevation,ForestFireIndex,Humidity,Latitude,Longitude,PrecipitationProbability,Temperature,WindSpeed
0,-14.444444,365.1504,1.0,10,34.1141,-118.4068,0,65,10
1,-17.777778,178.0032,0.0,66,41.8375,-87.6866,0,9,5
2,10.000000,2.1336,0.2,100,25.7840,-80.2101,0,50,6
3,-1.666667,17.9832,0.7,70,29.7860,-95.3885,0,38,5
4,-7.777778,153.9240,0.9,53,32.7935,-96.7667,0,33,0

In [ ]:
# 12
import os
from sklearn.preprocessing import StandardScaler
features = ['Dewpoint', 'Elevation', 'Humidity', 'Latitude', 'Longitude', 'PrecipitationProbability', 'Temperature', 'WindSpeed']
scaler = StandardScaler()

df[features] = df[features].astype('float64')
df[features] = scaler.fit_transform(df[features])  # mean = 0, and stddev = 1

df.head()

,Dewpoint,Elevation,ForestFireIndex,Humidity,Latitude,Longitude,PrecipitationProbability,Temperature,WindSpeed
0,-0.653183,0.281653,1.0,-2.269773,-0.457861,-1.285448,-0.282368,2.065681,1.300654
1,-1.029199,-0.200503,0.0,0.064395,0.882450,0.453258,-0.282368,-1.262516,0.049742
2,2.104270,-0.653604,0.2,1.481568,-1.903457,0.876414,-0.282368,1.174200,0.299924
3,0.788213,-0.612770,0.7,0.231121,-1.208954,0.017345,-0.282368,0.461014,0.049742
4,0.098850,-0.262539,0.9,-0.477466,-0.687036,-0.060659,-0.282368,0.163854,-1.201171

**Step 3: Create, train, and evaluate the neural network!**

In [ ]:
import joblib
joblib.dump(scaler, 'scaler.pkl')

['scaler.pkl']

In [ ]:
# 13
# Separate data back into train and test
x_train = df[pd.notnull(df['ForestFireIndex'])].drop(['ForestFireIndex'],axis=1)
x_train.head()

,Dewpoint,Elevation,Humidity,Latitude,Longitude,PrecipitationProbability,Temperature,WindSpeed
0,-0.653183,0.281653,-2.269773,-0.457861,-1.285448,-0.282368,2.065681,1.300654
1,-1.029199,-0.200503,0.064395,0.882450,0.453258,-0.282368,-1.262516,0.049742
2,2.104270,-0.653604,1.481568,-1.903457,0.876414,-0.282368,1.174200,0.299924
3,0.788213,-0.612770,0.231121,-1.208954,0.017345,-0.282368,0.461014,0.049742
4,0.098850,-0.262539,-0.477466,-0.687036,-0.060659,-0.282368,0.163854,-1.201171

In [ ]:
# 14
# Separate data back into train and test
y_train = df[pd.notnull(df['ForestFireIndex'])]['ForestFireIndex']
y_train.head()

0    1.0
1    0.0
2    0.2
3    0.7
4    0.9
Name: ForestFireIndex, dtype: float64

In [ ]:
# 15
# Separate data back into train and test
x_test = df[pd.isnull(df['ForestFireIndex'])].drop(['ForestFireIndex'],axis=1)
x_test.head()

,Dewpoint,Elevation,Humidity,Latitude,Longitude,PrecipitationProbability,Temperature,WindSpeed
0,0.662874,-0.656745,0.981389,-1.244703,0.282372,-0.282368,-0.014442,-1.201171
1,0.098850,-0.105485,0.231121,-0.486200,0.697632,-0.282368,-0.192739,0.049742
2,-0.966530,1.463484,-1.602868,0.056110,-1.011989,-0.282368,0.104422,-0.700806
3,0.725543,-0.641039,0.731300,-1.157084,0.087719,-0.282368,0.163854,-1.201171
4,-0.465175,-0.074074,0.647937,0.857131,0.550828,3.236617,-0.965356,1.300654

**Define a NN model**

In [ ]:
# 16
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout

from numpy.random import seed

In [ ]:
# 17
print(x_train.shape[1])

8

Dropout is a regularization method approximating concurrent training of many neural networks with various designs. During training, some layer outputs are ignored or dropped at random. This makes the layer appear and is regarded as having a different number of nodes and connectedness to the preceding layer.

In [ ]:
# 18
def create_model(act='relu', opt='Adam', dr=0.0):
# activation function = relu, gradient descent optimization = Adam

    model = Sequential()

    # create first hidden layer
    model.add(Dense(8, input_dim= x_train.shape[1], activation=act))

    # add dropout
    model.add(Dropout(dr))

    # create output layer
    model.add(Dense(1, activation='sigmoid'))

    model.compile(loss='mean_squared_error', optimizer=opt, metrics=['mae'])

    return model

In [ ]:
# 19
model = create_model(dr=0.2)
print(model.summary())

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 8)                   │              72 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 8)                   │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │               9 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 81 (324.00 B)

 Trainable params: 81 (324.00 B)

 Non-trainable params: 0 (0.00 B)

None

In [ ]:
# 20
# train model with 80/20 CV split
training = model.fit(x_train, y_train, epochs=500, batch_size=16, validation_split=0.2, verbose=0)
# validation_split = Fraction of the training data to be used as validation data

scores = model.evaluate(x_train, y_train)
print("validation MAE:", scores[1])

17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0401 - mae: 0.1440
validation MAE: 0.15304933488368988

In [ ]:
model.save('wildfire_risk_model.keras', include_optimizer=False)
from google.colab import files
files.download('wildfire_risk_model.keras')

In [ ]:
# 21
# model predict on test data
test['ForestFireIndex'] = model.predict(x_test)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step

In [ ]:
# 22
# Test the prediction result
s1 = model.predict(x_test)
print(s1[:6])

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[0.41450992]
 [0.20656286]
 [0.9678704 ]
 [0.5257182 ]
 [0.03932498]
 [0.4913521 ]]

In [ ]:
# 23
# model predict on test data
test['ForestFireIndex'] = model.predict(x_test)
test.head(20)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

,Latitude,Longitude,Elevation,Temperature,PrecipitationProbability,Dewpoint,Humidity,WindSpeed,ForestFireIndex
0,29.5800,-90.7059,0.9144,30,0,-2.777778,88,0,0.414510
1,33.9508,-83.3689,214.8840,27,0,-7.777778,70,5,0.206563
2,37.0758,-113.5752,823.8744,32,0,-17.222222,26,2,0.967870
3,30.0849,-94.1451,7.0104,33,0,-2.222222,82,0,0.525718
4,41.6916,-85.9627,227.0760,14,31,-12.777778,80,10,0.039325
5,30.2010,-93.2111,3.9624,33,0,-2.222222,82,0,0.491352
6,34.9333,-120.4431,74.9808,50,0,3.333333,63,0,0.887179
7,32.5995,-114.5491,56.0832,46,0,-16.111111,16,5,0.998847
8,38.8833,-94.8200,306.0192,12,0,-13.888889,77,3,0.122977
9,32.0243,-102.1147,847.0392,28,0,-13.333333,42,0,0.955684
10,40.4152,-104.7706,1476.1464,12,0,-16.111111,65,5,0.262087
11,33.8346,-118.3416,28.9560,50,0,-3.888889,38,5,0.969263
12,39.9197,-104.9438,1602.0288,18,0,-17.222222,46,12,0.579050
13,32.3265,-106.7893,1204.8744,22,0,-17.777778,37,1,0.982768
14,38.9472,-92.3268,237.1344,11,0,-14.444444,80,3,0.105820
15,33.8841,-117.9279,60.0456,60,0,-18.333333,8,10,0.998882
16,39.0877,-108.5673,1412.1384,16,0,-17.222222,51,5,0.464135
17,18.4054,-65.9792,9.1440,74,60,22.777778,96,10,0.666583
18,29.9977,-90.1780,0.9144,35,0,-1.111111,82,0,0.421193
19,33.8038,-117.8218,106.9848,64,0,-18.888889,7,20,0.998393